{{- if .Values.preDeploy.job.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.preDeploy.job.serviceAccount.name | default "parabol-predeploy" }}
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/name: parabol
    app.kubernetes.io/component: predeploy
    {{- with .Values.preDeploy.job.serviceAccount.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Release.IsUpgrade }}
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "-3"
    helm.sh/hook-delete-policy: before-hook-creation
    {{- end }}
    {{- if .Release.IsInstall }}
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-3"
    helm.sh/hook-delete-policy: before-hook-creation
    {{- end }}
    {{- with .Values.preDeploy.job.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
