{{- if .Values.parabolDeployment.env.mattermost.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mattermost-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  secret: {{ .Values.parabolDeployment.env.mattermost.mattermostSecret | b64enc | quote }}
{{- end -}}
