apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      annotations:
        {{- if .Values.monitoring.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
        {{ end }}
    spec:
      containers:
      - name: redis
        image: "{{ .Values.global.imageRegistry.host }}/{{ .Values.services.redis.image }}"
        ports:
          - containerPort: 6379
            name: redis
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 15
          timeoutSeconds: 5
        {{- if .Values.services.redis.localStorage.enabled }}  
        volumeMounts:
          - name: redis-persistent-storage
            mountPath: /data
        {{ end }}  
      {{- if .Values.monitoring.enabled }}      
      - name: redis-exporter
        image: "{{ .Values.global.imageRegistry.host }}/{{ .Values.services.redis.exporter }}"
        securityContext:
          runAsUser: 59000
          runAsGroup: 59000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: {{ .Values.monitoring.redis.metricsPort }}
            name: metrics
      {{ end }}      
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.services.redis.localStorage.enabled }}
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pvc
      {{ end }}    
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  annotations:
  labels:  
    app.kubernetes.io/part-of: parabol   
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  {{- if .Values.monitoring.enabled }}   
  - name: metrics
    port: {{ .Values.monitoring.redis.metricsPort }}
    targetPort: {{ .Values.monitoring.redis.metricsPort }}
  {{ end }}  
  selector:
    app: redis
---
{{- if .Values.services.redis.localStorage.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{ end }}

