{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: parabol-servicemonitor
  namespace: parabol
  labels:
    prometheus: default
spec:
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 25s
  namespaceSelector:
    matchNames:
      - parabol
  selector:
    matchLabels:
      app.kubernetes.io/part-of: parabol
{{ end }}      
