{{- if and .Values.monitoring.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: parabol-servicemonitor
  namespace: parabol
  labels:
    prometheus: default
spec:
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 25s
  namespaceSelector:
    matchNames:
      - parabol
  selector:
    matchLabels:
      app.kubernetes.io/part-of: parabol
{{- else }}
{{- if .Values.monitoring.enabled }}
# Skipping ServiceMonitor 'parabol-servicemonitor' because CRD 'monitoring.coreos.com/v1' is not installed
{{- end }}
{{- end }}
