{{- if .Values.textEmbeddingsInference.deployment.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.textEmbeddingsInference.deployment.serviceAccount.name | default "parabol-text-embeddings-inference" }}
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/name: parabol
    app.kubernetes.io/component: text-embeddings-inference
    {{- with .Values.textEmbeddingsInference.deployment.serviceAccount.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.textEmbeddingsInference.deployment.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
