{{- if .Values.services.parabol.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.services.parabol.serviceAccount.name | default "parabol-webserver" }}
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/name: parabol
    app.kubernetes.io/component: webserver
    {{- with .Values.services.parabol.serviceAccount.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.services.parabol.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
