apiVersion: v1
kind: Service
metadata:
  name: parabol-service
spec:
  type: ClusterIP
  ports:
  - name: webserver
    port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/component: webserver
    app.kubernetes.io/name: parabol
