{{- $nginxEnabled := false }}
{{- if .Values.parabolDeployment.nginx.enabled }}
  {{- if eq .Values.parabolDeployment.env.fileStoreProvider "local" }}
    {{- $nginxEnabled = true }}
  {{- else if and (eq .Values.parabolDeployment.env.fileStoreProvider "s3") .Values.parabolDeployment.env.proxyCDN }}
    {{- $nginxEnabled = true }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: parabol-service
spec:
  type: ClusterIP
  ports:
  - name: webserver
    port: 3000
    {{- if $nginxEnabled }}
    targetPort: nginx
    {{- else }}
    targetPort: webserver
    {{- end }}

  selector:
    app.kubernetes.io/component: webserver
    app.kubernetes.io/name: parabol
