{{- $pkg := "parabol" }}
{{- $pkgValues := get .Values $pkg | default dict }}
{{- $fluxSettings := merge (default dict $pkgValues.flux) (default dict .Values.flux) -}}
{{- if $pkgValues.enabled }}

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $pkg }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}
    {{- include "commonLabels" . | nindent 4 }}
spec:
  targetNamespace: {{ default .Release.Namespace $pkg }}
  chart:
    spec:
      chart: {{ $pkgValues.git.path | default "charts/parabol" }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: {{ $pkg }}
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettings | nindent 2 }}

  {{- if $pkgValues.postRenderers }}
  postRenderers:
{{- toYaml $pkgValues.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-{{ $pkg }}-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-{{ $pkg }}-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-{{ $pkg }}-values
      kind: Secret
      valuesKey: "overlays"
  {{- if or .Values.istio.enabled .Values.monitoring.enabled }}
  dependsOn:
  {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    - name: istio-crds
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.monitoring.enabled }}
    - name: grafana
      namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
