---
apiVersion: v1
kind: ConfigMap
metadata:
  name: parabol-config
data:
  {{- range $key, $value := .Values.parabolDeployment.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parabol-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parabol
  template:
    metadata:
      labels:
        app: parabol
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
      containers:
      - name: parabol
        command: ["/bin/sh"]
        args: ["-c", "sleep 15s && NODE_ENV=production && DEBUG=* && node ./dist/preDeploy.js && node ./dist/web.js & node ./dist/gqlExecutor.js"]
        image: "{{ .Values.imageRegistry.host }}/{{ .Values.services.parabol.image }}"
        env:
          {{- with .Values.parabolDeployment.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: parabol-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: parabol