---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  {{- range $key, $value := .Values.postgresDeployment.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 26
        runAsGroup: 26
      containers:
      - name: postgres
        image: "{{ .Values.imageRegistry.host }}/{{ .Values.services.postgres.image }}"
        env:
          {{- with .Values.postgresDeployment.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres